In [1]:
import pandas as pd
import json

In [2]:
df = pd.read_csv("csv_sources/sources_flat.csv")
df.head(270)

,Country,ISO,Year,Total,Coal,Oil,Gas,Cement,Flaring,Other,Per Capita
0,Afghanistan,AFG,1750,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
1,Afghanistan,AFG,1751,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
2,Afghanistan,AFG,1752,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
3,Afghanistan,AFG,1753,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
4,Afghanistan,AFG,1754,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
...,...,...,...,...,...,...,...,...,...,...,...
265,Afghanistan,AFG,2015,CDIAC 2022,CDIAC 2022,CDIAC 2022,CDIAC 2022,Andrew cement,CDIAC 2022,[NONE],CDIAC 2022 and UN population
266,Afghanistan,AFG,2016,CDIAC 2022,CDIAC 2022,CDIAC 2022,CDIAC 2022,Andrew cement,CDIAC 2022,[NONE],CDIAC 2022 and UN population
267,Afghanistan,AFG,2017,CDIAC 2022,CDIAC 2022,CDIAC 2022,CDIAC 2022,Andrew cement,CDIAC 2022,[NONE],CDIAC 2022 and UN population
268,Afghanistan,AFG,2018,CDIAC 2022,CDIAC 2022,CDIAC 2022,CDIAC 2022,Andrew cement,CDIAC 2022,[NONE],CDIAC 2022 and UN population
269,Afghanistan,AFG,2019,CDIAC 2022,CDIAC 2022,CDIAC 2022,CDIAC 2022,Andrew cement,CDIAC 2022,[NONE],CDIAC 2022 and UN population

In [3]:
del df["ISO"]
df.head(270)

,Country,Year,Total,Coal,Oil,Gas,Cement,Flaring,Other,Per Capita
0,Afghanistan,1750,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
1,Afghanistan,1751,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
2,Afghanistan,1752,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
3,Afghanistan,1753,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
4,Afghanistan,1754,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
...,...,...,...,...,...,...,...,...,...,...
265,Afghanistan,2015,CDIAC 2022,CDIAC 2022,CDIAC 2022,CDIAC 2022,Andrew cement,CDIAC 2022,[NONE],CDIAC 2022 and UN population
266,Afghanistan,2016,CDIAC 2022,CDIAC 2022,CDIAC 2022,CDIAC 2022,Andrew cement,CDIAC 2022,[NONE],CDIAC 2022 and UN population
267,Afghanistan,2017,CDIAC 2022,CDIAC 2022,CDIAC 2022,CDIAC 2022,Andrew cement,CDIAC 2022,[NONE],CDIAC 2022 and UN population
268,Afghanistan,2018,CDIAC 2022,CDIAC 2022,CDIAC 2022,CDIAC 2022,Andrew cement,CDIAC 2022,[NONE],CDIAC 2022 and UN population
269,Afghanistan,2019,CDIAC 2022,CDIAC 2022,CDIAC 2022,CDIAC 2022,Andrew cement,CDIAC 2022,[NONE],CDIAC 2022 and UN population

In [4]:
data_list = []

In [5]:
for index, row in df.iterrows():
    data_dict = {
        'Country' : row['Country'],
        'Year' : row['Year'],
        'Total' : row['Total'],
        'Coal' : row['Coal'],
        'Oil' : row['Oil'],
        'Gas' : row['Gas'],
        'Cement' : row['Cement'],
        'Flaring' : row['Flaring'],
        'Other' : row['Other'],
        'Per Capita' : row['Per Capita'] 
    }
    data_list.append(data_dict)

In [6]:
json_data = json.dumps(data_list)

In [7]:
with open("static/js/sources.js", "w") as js_file:
    js_file.write(f"const sources = {json_data};")